# Generated by Django 3.2.3 on 2021-07-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phoneno', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=18)),
                ('username', models.CharField(max_length=18)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
            ],
        ),
    ]
